title: ICS4U Student Portfolio
description: A simple Markdown-based website for ICS4U students
theme: 'jekyll-theme-merlot'
remote_theme: pages-themes/merlot@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
